### ISSUE TITLE
Broken API how-to link

### ISSUE THREAD

**Issue by adamhsparks** [AgrDataSci/ag5Tools#10]
The <https://cds.climate.copernicus.eu/api-how-to> link in the README that appears several times results in a "Page not found", not documentation as expected.

**Comment by adamhsparks** [comment]
Maybe this is the resource that is intended? <https://cds.climate.copernicus.eu/how-to-api>?

**Comment by dbrownf** [comment]
Yes, the URLs were changed in the Copernicus website. I have updated them in the README file. Thank you for letting me know.

**Comment by adamhsparks** [comment]
I thought that's what had happened. 

cheers!
