### ISSUE TITLE
Error with extraction of wind variable

### ISSUE THREAD

**Issue by howardvanmeer** [AgrDataSci/ag5Tools#6]
Dear David 

It's me again, I downloaded all de files but when a want to extract "wind" from netcdf daily files I get de following error:

****dk_wind <- ag5_extract(coords = c(9.546480, 56.437384), 
+                        dates = c("2015-01-01", "2023-12-31"), variable = "10m_wind_speed", statistic="24_hour_mean",path = "D:/ERA5")
Error in get_file_path(date_to_search = X, variable, statistic, time,  : 
  File not found****
 
All the other variables i can extract without any problem. My netcdf files are stored on a external drive because of size but that didn't give any problems for the other variables. What is the correct way for Variable and statistic for wind data sets?

Kind regards,
Howard

**Comment by dbrownf** [comment]
Hi Howard,

Thanks for pointing this out. There were some errors in both the documentation and the code. I fixed them in the current development version.

Could you please install the development version and try again. In your example the variable and statistic parameters now should be:
```
dates = c("2015-01-01", "2023-12-31"), 
variable = "Wind-Speed-10m", 
statistic = "24_hour_mean",
path = "D:/ERA5")
```
David

**Comment by howardvanmeer** [comment]
Hi David with that it worked! Only statistic must be "Mean" NOT "24_hour_mean"
Thank you very much!
Howard

**Comment by dbrownf** [comment]
Great! Yes, I forgot to change the statistic as well. Thanks
Should be like this:
```
dates = c("2015-01-01", "2023-12-31"), 
variable = "Wind-Speed-10m", 
statistic = "Mean",
path = "D:/ERA5")
```
